variables:
- group: my-variable-group

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-latest'
    continueOnError: true
  - script: |
      export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
      export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
      export AWS_DEFAULT_REGION=$AWS_REGION
      aws lambda update-function-code --function-name  my-function --zip-file fileb://my-function.zip
    
# - stage: dev_deploy
#   jobs:
#   - deployment: dev_deploy
#     pool:
#       vmImage: 'Ubuntu-16.04'
#     environment: 'dev-hello'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - script: - script: aws lambda update-function-code --function-name  my-function --zip-file fileb://my-function.zip
          
# - stage: qa_deploy
#   jobs:
#   - deployment: qa_deploy
#     pool:
#       vmImage: 'Ubuntu-16.04'
#     environment: 'qa-hello'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - script: echo "hello, qa world !!!"
