############################# pipeline with multiple jobs in one stage ###############
variables:
- group: my-variable-group
pool:
  vmImage: 'Ubuntu-latest'

stages:
- stage: deploy_lambda_code
  jobs:
  - job: create_lambda_layer
    pool:
      vmImage: 'Ubuntu-latest'
    steps:
      - script: | 
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
          export AWS_DEFAULT_REGION=$AWS_REGION
          set AWS_DEFAULT_PROFILE=aws-engineering
          aws lambda publish-layer-version --layer-name my-layer --description "My layer" --zip-file  "fileb://layer.zip"  --compatible-runtimes python3.6 python3.7
  - job: dev_lambda_function_update
    steps:
      - script: |
          cd apps/trigger-engine/
          zip -r lambda_function.zip .
          aws lambda update-function-code --function-name  <my-function> --zip-file fileb://lambda_function.zip
          aws lambda update-function-configuration --function-name <my-function> --layers <layer arn-1> < layer arn -2>        
  - job: qa_lambda_function_update
    steps:
      - script: | 
          cd apps/trigger-engine/
          zip -r lambda_function.zip .
          aws lambda update-function-code --function-name  Replace_with_lambda_function_Name --zip-file fileb://lambda_function.zip

############################################## pipeline with single job multiple stages ################

# variables:
# - group: my-variable-group

# stages:
# - stage: dev_lambda_function_update
#   jobs:
#   - job: deploy_code
#     pool:
#       vmImage: 'Ubuntu-latest'
#     steps:
#       - script: | 
#           export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
#           export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
#           export AWS_DEFAULT_REGION=$AWS_REGION
#           cd apps/trigger-engine/
#           zip -r lambda_function.zip .
#           aws lambda update-function-code --function-name  Replace_with_lambda_function_Name --zip-file fileb://lambda_function.zip
# - stage: qa_lambda_function_update
#   jobs:
#   - job: deploy_code
#     pool:
#       vmImage: 'Ubuntu-latest'
#     steps:
#       - script: | 
#           export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
#           export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
#           export AWS_DEFAULT_REGION=$AWS_REGION
#           cd apps/trigger-engine/
#           zip -r lambda_function.zip .
#           aws lambda update-function-code --function-name  Replace_with_lambda_function_Name --zip-file fileb://lambda_function.zip
