############################# pipeline with multiple jobs in one stage ###############
variables:
- group: my-variable-group

stages:
- stage: deploy_lambda_code
  jobs:
  - job: dev_lambda_function_update
    pool:
      vmImage: 'Ubuntu-latest'
    steps:
      - script: | 
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
          export AWS_DEFAULT_REGION=$AWS_REGION
          zip -j lambda_function.zip apps/trigger-engine/*.* 
          aws lambda update-function-code --function-name  my-function --zip-file fileb://lambda_function.zip
  - job: qa_lambda_function_update
    pool:
      vmImage: 'Ubuntu-latest'
    steps:
      - script: | 
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
          export AWS_DEFAULT_REGION=$AWS_REGION
          zip -j lambda_function.zip apps/trigger-engine/*.* 
          aws lambda update-function-code --function-name  my-function --zip-file fileb://lambda_function.zip

############################################## pipeline with single job multiple stages ################

# variables:
# - group: my-variable-group

# stages:
# - stage: dev_lambda_function_update
#   jobs:
#   - job: deploy_code
#     pool:
#       vmImage: 'Ubuntu-latest'
#     steps:
#       - script: | 
#           export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
#           export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
#           export AWS_DEFAULT_REGION=$AWS_REGION
#           zip -j lambda_function.zip apps/trigger-engine/*.* 
#           aws lambda update-function-code --function-name  my-function --zip-file fileb://lambda_function.zip
# - stage: qa_lambda_function_update
#   jobs:
#   - job: deploy_code
#     pool:
#       vmImage: 'Ubuntu-latest'
#     steps:
#       - script: | 
#           export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
#           export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
#           export AWS_DEFAULT_REGION=$AWS_REGION
#           zip -j lambda_function.zip apps/trigger-engine/*.* 
#           aws lambda update-function-code --function-name  my-function --zip-file fileb://lambda_function.zip
