Resources:

  lambdafnrole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambdafnrole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
                

  function2:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: function2
      Role: !GetAtt lambdafnrole.Arn
      Runtime: python3.7
      Handler: index.my_handler
      Code:
        ZipFile: |
          def my_handler(event, context):
            message = 'Hello Lambda World!'
            return message

  function1:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: function1
      Role: !GetAtt lambdafnrole.Arn
      Runtime: python3.7
      Handler: index.my_handler
      Code:
        ZipFile: |
          def my_handler(event, context):
            message = 'Hello Lambda World!'
            return message