#!/bin/bash
sudo yum update -y
sudo yum install -y httpd
sudo systemctl start httpd
sudo systemctl enable httpd
INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
VPC_ID=$(curl -s http://169.254.169.254/latest/meta-data/network/interfaces/macs/$(curl -s http://169.254.169.254/latest/meta-data/network/interfaces/macs/)/vpc-id)
echo “Hello World from $(INSTANCE_ID) located at vpc $9VPC_ID) at zone  $(ec2-metadata -z)” > /var/www/html/index.html
sudo systemctl restart httpd


echo “Hello World from $(ec2-metadata -i) located at $(ec2-metadata -z)” >> /var/www/html/index.html
echo “Hello World from $(hostname -f)” >> /var/www/html/index.html


sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker -y
systemctl start docker
docker pull httpd
https://code.mendhak.com/lambda-docker-hello-world/

